service: minerva-figure-services 
provider:
  name: aws
  runtime: python3.6
  managedPolicyArns:
    - "arn:aws:iam::292075781285:policy/read_minerva_metadata"
    - "arn:aws:iam::292075781285:policy/access_minerva_figures"
    - "arn:aws:iam::292075781285:policy/create_minerva_figure_services"
functions:
  render:
    handler: handler.render
    events:
      - http:
          cors: true
          method: get
          path: webgateway/render_image/{token}/{uuid}/{z}/{t}/
          contentHandling: CONVERT_TO_BINARY
          request:
            parameters:
              querystrings:
                c: true
                m: false
                maps: false
              paths:
                token: true
                uuid: true
                z: true
                t: true
plugins:
  - serverless-attach-managed-policy
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-apigwy-binary
  - serverless-apigw-binary
custom:
  pythonRequirements:
    dockerizePip: non-linux
    dockerFile: Dockerfile
  apigwBinary:
    types:
      - "image/png"
