service: minerva-figure-services 
provider:
  name: aws
  runtime: python3.6
  managedPolicyArns:
    - "arn:aws:iam::292075781285:policy/access_minerva_figures"
    - "arn:aws:iam::292075781285:policy/create_minerva_figure_services"
functions:
  render:
    handler: handler.render
    events:
      - http:
          cors: true
          method: get
          path: render
          contentHandling: CONVERT_TO_BINARY
plugins:
  - serverless-attach-managed-policy
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-apigwy-binary
custom:
  pythonRequirements:
    dockerizePip: non-linux
    dockerFile: Dockerfile
